name: Debug workflow

on: [push, pull_request]

jobs:
  test:
    name: Lint and test
    runs-on: ubuntu-latest
    environment: prod
    env:
      image: djvue/urfu-deployments:post-classifier-latest
    steps:
    - uses: actions/checkout@v2
    # TODO: add Flake8
    #- name: Flake8
    #  run: docker run --rm --entrypoint /bin/bash -t $image -c "flake8"
    - name: Download datasets
      run: mkdir data && docker run --rm
        -v $PWD/data:/app/data
        --entrypoint /bin/bash
        -t $image -c "dvc remote modify --local minio access_key_id \"${{ secrets.DVC_S3_ACCESS_KEY }}\"
        && dvc remote modify --local minio secret_access_key \"${{ secrets.DVC_S3_SECRET_KEY }}\"
        && cat .dvc/config.local
        && dvc pull"
    - name: Train model
      run: docker run --rm --entrypoint /bin/bash -t $image -c "python train_model.py"
    - name: Tests
      run: docker run --rm --entrypoint /bin/bash -t $image -c "python -m pytest"