name: Train and deploy ML model. Update git repository with new model hash for dvc

on: workflow_dispatch

jobs:
  train_and_deploy_model:
    name: Train and deploy model
    runs-on: ubuntu-latest
    environment: prod
    env:
      image: djvue/urfu-deployments:post-classifier-${{ github.sha }}
    steps:
    - uses: actions/checkout@v2
    - name: Download datasets
      run: mkdir data && docker run --rm
        -v $PWD/data:/app/data
        --entrypoint /bin/bash
        -t $image -c "dvc remote modify --local minio access_key_id \"${{ secrets.DVC_S3_ACCESS_KEY }}\"
        && dvc remote modify --local minio secret_access_key \"${{ secrets.DVC_S3_SECRET_KEY }}\"
        && dvc pull"
    - name: Train model
      run: docker run --rm -v $PWD/data:/app/data --entrypoint /bin/bash -t $image -c "python train_model.py"
    - name: Add models to dvc
      run: docker run --rm
        -v $PWD/data:/app/data
        --entrypoint /bin/bash
        -t $image -c "dvc remote modify --local minio access_key_id \"${{ secrets.DVC_S3_ACCESS_KEY }}\"
        && dvc remote modify --local minio secret_access_key \"${{ secrets.DVC_S3_SECRET_KEY }}\"
        && dvc add data
        && dvc push"
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: ML model update
    # after this commit project redeploy will be triggered automatically